# Generated by Django 5.2 on 2025-07-01 09:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0014_alter_subject_status_alter_subject_teacher'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', help_text='Group of the lessons', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the lesson', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the lesson')),
                ('average_points', models.PositiveIntegerField(default=1, help_text='Grade of the lesson')),
                ('maximum_points', models.PositiveIntegerField(default=100, help_text='Maximum points of the lesson')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('delayed', 'Delayed'), ('on schedule', 'On Schedule')], default='pending', max_length=20)),
                ('quarter', models.PositiveIntegerField(default=1, help_text='Quarter of the lesson', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('unit', models.PositiveIntegerField(default=1, help_text='Unit of the lesson', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(blank=True, help_text='Subject of the lesson', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_subject', to='home.subject')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_group', to='lesson.lessongroup')),
            ],
            options={
                'verbose_name': 'Lesson',
                'verbose_name_plural': 'Lessons',
                'ordering': ['created_at', 'updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_points', models.PositiveIntegerField(default=0, help_text='Points of the lesson')),
                ('to_points', models.PositiveIntegerField(default=100, help_text='Points of the lesson')),
                ('comment_text', models.TextField(help_text='Template comment text')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_comment', to='lesson.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='StudentGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.PositiveIntegerField(default=0, help_text='Grade of the lesson')),
                ('points', models.PositiveIntegerField(default=0, help_text='Points of the lesson')),
                ('comment', models.TextField(blank=True, help_text='Comment of the lesson')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='lesson_grade', to='lesson.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='lesson_student_grade', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
