# Generated by Django 5.2 on 2025-08-23 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0004_alter_topic_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
