# Generated by Django 5.2 on 2025-09-01 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0026_student_academic_year'),
        ('lesson', '0005_alter_topic_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentgrade',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='studentgrade',
            name='student',
        ),
        migrations.AddField(
            model_name='topic',
            name='comment_template',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='topicgrade',
            name='comment_selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='topic',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Percent weight in lesson (must sum to 100% for all siblings under same parent)', max_digits=5),
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together={('lesson', 'title')},
        ),
        migrations.CreateModel(
            name='MergedLessonComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(help_text='Template comment text')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_comment', to='lesson.lesson')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_comment', to='authentication.student')),
            ],
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='StudentGrade',
        ),
    ]
