# Generated by Django 5.2 on 2025-09-10 05:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0006_remove_studentgrade_lesson_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='unit',
            field=models.PositiveIntegerField(default=1, help_text='Unit of the lesson', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(15)]),
        ),
    ]
