# Generated by Django 5.2 on 2025-08-24 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0006_alter_topic_title'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together={('lesson', 'title')},
        ),
    ]
