# Generated by Django 5.2 on 2026-01-25 10:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0031_remove_student_classroom_remove_teacher_classroom_and_more'),
        ('home', '0023_gradelevel_remove_subject_academic_year_and_more'),
        ('lesson', '0007_alter_lesson_unit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='group',
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['date', 'order'], 'verbose_name': 'Lesson', 'verbose_name_plural': 'Lessons'},
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='average_points',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='maximum_points',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='subject',
        ),
        migrations.AddField(
            model_name='lesson',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='offering',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='home.subjectoffering'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='AssessmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('assessment_type', models.CharField(choices=[('homework', 'Homework'), ('quiz', 'Quiz'), ('test', 'Test'), ('exam', 'Exam'), ('project', 'Project'), ('participation', 'Participation'), ('other', 'Other')], default='homework', max_length=20)),
                ('max_points', models.PositiveIntegerField(default=10)),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, help_text='Weight for weighted grading strategy', max_digits=5)),
                ('quarter', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(blank=True, help_text='Optional: link to specific lesson', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_items', to='lesson.lesson')),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_items', to='home.subjectoffering')),
            ],
            options={
                'ordering': ['quarter', 'date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StudentScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_earned', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('comment', models.TextField(blank=True)),
                ('graded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='lesson.assessmentitem')),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_scores', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='authentication.student')),
            ],
            options={
                'unique_together': {('student', 'assessment_item')},
            },
        ),
        migrations.DeleteModel(
            name='LessonGroup',
        ),
    ]
