# Generated by Django 5.2 on 2025-08-30 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0007_alter_topic_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='comment_template',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
