# Generated by Django 5.2 on 2025-08-30 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0008_topic_comment_template_alter_topic_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicgrade',
            name='comment_selected',
            field=models.BooleanField(default=False),
        ),
    ]
