# Generated by Django 5.2 on 2026-01-29 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0008_remove_lesson_group_alter_lesson_options_and_more'),
    ]

    operations = [
        # First: Add the new Topic.order field
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='topic',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Sequence order for accumulation logic (lower = earlier)'),
        ),
        # Then: Delete AssessmentItem and StudentScore models entirely
        # (This handles all constraints and fields automatically)
        migrations.DeleteModel(
            name='StudentScore',
        ),
        migrations.DeleteModel(
            name='AssessmentItem',
        ),
    ]
