# Generated by Django 5.2 on 2025-08-30 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0026_student_academic_year'),
        ('lesson', '0009_topicgrade_comment_selected'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GeneralLessonComment',
            new_name='MergedLessonComment',
        ),
    ]
