# Generated by Django 5.2 on 2026-02-05 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0009_remove_studentscore_assessment_item_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together={('lesson', 'parent', 'title')},
        ),
    ]
