# Generated by Django 5.2 on 2025-08-31 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0010_rename_generallessoncomment_mergedlessoncomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Percent weight in lesson (must sum to 100% for all siblings under same parent)', max_digits=5),
        ),
    ]
