# Generated by Django 5.2 on 2026-05-28 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0033_historicalstudent'),
        ('lesson', '0011_historicallesson_historicaltopic_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='topicgrade',
            unique_together={('topic', 'student', 'is_deleted')},
        ),
    ]
