# Generated by Django 5.2 on 2026-05-28 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0033_historicalstudent'),
        ('lesson', '0012_alter_topicgrade_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltopicgrade',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='historicaltopicgrade',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='historicaltopicgrade',
            name='is_deleted',
        ),
        migrations.AlterUniqueTogether(
            name='topicgrade',
            unique_together={('topic', 'student')},
        ),
        migrations.RemoveField(
            model_name='topicgrade',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='topicgrade',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='topicgrade',
            name='is_deleted',
        ),
    ]
