# Generated by Django 5.2 on 2026-05-28 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0013_remove_historicaltopicgrade_deleted_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltopic',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='historicaltopic',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='historicaltopic',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='is_deleted',
        ),
    ]
