# Generated by Django 5.2 on 2026-07-02 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0014_remove_historicaltopic_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mergedlessoncomment',
            name='is_merged',
            field=models.BooleanField(default=False),
        ),
    ]
