# Generated by Django 5.2 on 2026-08-11 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lesson", "0016_schedulesession_scheduleattendance_subjectschedule_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="schedulesession",
            unique_together={("schedule", "order", "weekday")},
        ),
    ]
