# Generated by Django 5.2 on 2026-08-18 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0035_historicalstudent_medical_features_and_more"),
        ("lesson", "0018_homework_homeworkgrade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homeworkgrade",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="homework_grades",
                to="authentication.student",
            ),
        ),
    ]
