# Generated by Django 5.2 on 2026-08-19 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0035_historicalstudent_medical_features_and_more"),
        ("lesson", "0019_alter_homeworkgrade_student"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="homeworkgrade",
            unique_together={("homework", "student")},
        ),
    ]
