# Generated by Django 5.2 on 2026-08-20 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lesson", "0020_alter_homeworkgrade_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="homeworkgrade",
            name="comments",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="homeworkgrade",
            name="grade",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
