# Generated by Django 5.2 on 2026-08-31 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0029_alter_subjectgrade_comments_alter_subjectgrade_grade"),
        ("lesson", "0021_homeworkgrade_comments_alter_homeworkgrade_grade"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="schedulesession",
            options={"ordering": ["schedule", "weekday"]},
        ),
        migrations.AlterUniqueTogether(
            name="schedulesession",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="subjectschedule",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="subjectschedule",
            name="offering",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedules",
                to="home.subjectoffering",
            ),
        ),
        migrations.RemoveField(
            model_name="schedulesession",
            name="order",
        ),
    ]
