# Generated by Django 5.2 on 2026-08-31 10:06

import datetime

from django.db import migrations, models

LESSON_LENGTH = datetime.timedelta(minutes=45)
FIRST_SESSION_START = datetime.time(8, 0)


def spread_session_times(apps, schema_editor):
    """Give every session a distinct slot within its (schedule, weekday) group.

    ``order`` was dropped in 0022, so there is nothing left to derive real times
    from; sessions are laid out back to back from 08:00 purely so the new unique
    constraint can be applied to existing rows.
    """
    ScheduleSession = apps.get_model('lesson', 'ScheduleSession')

    previous_group = None
    slot = 0
    for session in ScheduleSession.objects.order_by('schedule_id', 'weekday', 'id'):
        group = (session.schedule_id, session.weekday)
        slot = slot + 1 if group == previous_group else 0
        previous_group = group

        start = datetime.datetime.combine(datetime.date.min, FIRST_SESSION_START) + slot * LESSON_LENGTH
        session.time_start = start.time()
        session.time_end = (start + LESSON_LENGTH).time()
        session.save(update_fields=['time_start', 'time_end'])


class Migration(migrations.Migration):

    dependencies = [
        ("lesson", "0022_alter_schedulesession_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedulesession",
            name="time_start",
            field=models.TimeField(default=FIRST_SESSION_START),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="schedulesession",
            name="time_end",
            field=models.TimeField(default=datetime.time(8, 45)),
            preserve_default=False,
        ),
        migrations.RunPython(spread_session_times, migrations.RunPython.noop),
        migrations.AlterModelOptions(
            name="schedulesession",
            options={"ordering": ["schedule", "weekday", "time_start", "time_end"]},
        ),
        migrations.AlterUniqueTogether(
            name="schedulesession",
            unique_together={("schedule", "time_start", "time_end", "weekday")},
        ),
    ]
