# Generated by Django 5.2 on 2026-09-02 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0029_alter_subjectgrade_comments_alter_subjectgrade_grade"),
        ("lesson", "0023_schedulesession_time_start_schedulesession_time_end_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subjectschedule",
            name="class_group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedules",
                to="home.classgroup",
            ),
        ),
    ]
