# Generated by Django 5.2 on 2026-09-04 13:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0036_add_new_roles"),
        ("home", "0030_alter_enrollment_options_and_more"),
        ("lesson", "0024_subjectschedule_class_group"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="quartergradesnapshot",
            name="lesson_quar_student_af8283_idx",
        ),
        migrations.AlterUniqueTogether(
            name="quartergradesnapshot",
            unique_together={("student", "offering", "quarter")},
        ),
        migrations.AddIndex(
            model_name="quartergradesnapshot",
            index=models.Index(
                fields=["student", "offering"], name="lesson_quar_student_7f1a99_idx"
            ),
        ),
        migrations.RemoveField(
            model_name="quartergradesnapshot",
            name="academic_year",
        ),
    ]
