# Generated by Django 5.2 on 2026-09-17 09:53

import django.db.models.deletion
from django.db import migrations, models


def backfill(apps, schema_editor):
    """Derive each row's school from whichever FK it happens to have.

    SubjectSchedule today: 93 rows reach a school via `offering`, 1 via
    `class_group`, and 8 have neither — those 8 are the school-wide schedules
    that a join-based scope would have hidden from everyone. They fall back to
    school #1, which is where all current data lives.
    """
    School = apps.get_model('authentication', 'School')
    school = School.objects.filter(slug='muzafar_alimbayev').first()
    if school is None:
        return

    SubjectSchedule = apps.get_model('lesson', 'SubjectSchedule')
    for row in SubjectSchedule.objects.select_related(
        'offering__class_group', 'class_group',
    ).iterator():
        derived = None
        if row.offering_id and row.offering.class_group_id:
            derived = row.offering.class_group.school_id
        elif row.class_group_id:
            derived = row.class_group.school_id
        row.school_id = derived or school.pk
        row.save(update_fields=['school'])

    MergedLessonComment = apps.get_model('lesson', 'MergedLessonComment')
    for row in MergedLessonComment.objects.select_related(
        'lesson__offering', 'student__user',
    ).iterator():
        derived = None
        if row.lesson_id and row.lesson.offering_id:
            derived = row.lesson.offering.school_id
        elif row.student_id:
            derived = row.student.user.school_id
        row.school_id = derived or school.pk
        row.save(update_fields=['school'])


def unbackfill(apps, schema_editor):
    for model in ('SubjectSchedule', 'MergedLessonComment'):
        apps.get_model('lesson', model).objects.update(school=None)


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0039_auth_school_columns"),
        # the backfill reads offering.school / class_group.school
        ("home", "0035_school_columns"),
        (
            "lesson",
            "0025_remove_quartergradesnapshot_lesson_quar_student_af8283_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="mergedlessoncomment",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="merged_lesson_comments",
                to="authentication.school",
            ),
        ),
        migrations.AddField(
            model_name="subjectschedule",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subject_schedules",
                to="authentication.school",
            ),
        ),
        migrations.RunPython(backfill, unbackfill),
    ]
