# Generated by Django 5.2 on 2026-09-17 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0040_school_not_null"),
        ("lesson", "0026_school_columns"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mergedlessoncomment",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="merged_lesson_comments",
                to="authentication.school",
            ),
        ),
        migrations.AlterField(
            model_name="subjectschedule",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subject_schedules",
                to="authentication.school",
            ),
        ),
    ]
