# Generated by Django 5.2 on 2026-05-05 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0033_historicalstudent'),
        ('home', '0025_historicalenrollment_homeroomteacherassignment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.PositiveSmallIntegerField(help_text='Quarter number (1-4)')),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('kk', 'Қазақша'), ('en', 'English')], default='ru', max_length=2)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=12)),
                ('report_data', models.JSONField(blank=True, help_text='Structured report sections as JSON', null=True)),
                ('input_snapshot', models.JSONField(default=dict, help_text='Snapshot of student data sent to AI at generation time')),
                ('model_used', models.CharField(blank=True, default='', max_length=50)),
                ('tokens_used', models.PositiveIntegerField(blank=True, null=True)),
                ('generation_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.academicyear')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='authentication.student')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student', '-created_at'], name='student_rep_student_84acb0_idx'), models.Index(fields=['student', 'academic_year', 'quarter'], name='student_rep_student_28cfac_idx')],
            },
        ),
    ]
