# Generated by Django 5.2 on 2026-05-31 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentreport',
            name='language',
            field=models.CharField(choices=[('ru', 'Русский'), ('kz', 'Қазақша'), ('en', 'English')], default='ru', max_length=2),
        ),
    ]
