# Generated by Django 5.2 on 2026-04-29 11:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0031_remove_student_classroom_remove_teacher_classroom_and_more'),
        ('home', '0024_remove_gradelevel_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('olympiad', 'Subject Olympiad'), ('additional_education', 'Additional Education'), ('extracurricular', 'Extracurricular Activity'), ('project', 'Project')], max_length=30)),
                ('award_type', models.CharField(blank=True, help_text='e.g. Gold Medal, 1st Place Diploma', max_length=255)),
                ('place', models.CharField(blank=True, help_text='e.g. City, Regional, National, International', max_length=255)),
                ('role', models.CharField(blank=True, help_text='e.g. Class President, Club Leader', max_length=255)),
                ('duration', models.CharField(blank=True, help_text='e.g. Sep 2025 - May 2026', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description or result/comments for extracurricular')),
                ('certificate', models.FileField(blank=True, null=True, upload_to='achievements/certificates/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='home.academicyear')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='authentication.student')),
                ('subject', models.ForeignKey(blank=True, help_text='Only for olympiad category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achievements', to='home.subject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClubEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('club_name', models.CharField(max_length=255)),
                ('plan', models.TextField(blank=True)),
                ('criteria', models.TextField(blank=True)),
                ('total_sessions', models.PositiveIntegerField(default=0)),
                ('attended_sessions', models.PositiveIntegerField(default=0)),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_entries', to='home.academicyear')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_entries', to='authentication.student')),
            ],
            options={
                'ordering': ['academic_year', 'month', 'club_name'],
            },
        ),
        migrations.CreateModel(
            name='ReadingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='achievements/book_covers/')),
                ('month', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('pages_read', models.PositiveIntegerField(default=0)),
                ('test_score', models.FloatField(blank=True, help_text='Test result for this book (0-100)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_entries', to='home.academicyear')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_entries', to='authentication.student')),
            ],
            options={
                'ordering': ['academic_year', 'month', 'title'],
            },
        ),
    ]
