# Generated by Django 5.2 on 2026-08-03 08:04

import apps.achievement.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("achievement", "0004_club_clubsession_clubattendance_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attachment",
            name="file",
            field=models.FileField(
                upload_to="achievements/attachments/%Y/%m/",
                validators=[
                    apps.achievement.models.validate_attachment_size,
                    apps.achievement.models.validate_attachment_format,
                ],
            ),
        ),
    ]
