# Generated by Django 5.2 on 2026-08-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("achievement", "0005_alter_attachment_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("active", "Active"),
                    ("deleted", "Deleted"),
                    ("finished", "Finished"),
                ],
                default="pending",
                max_length=50,
            ),
        ),
    ]
