# Generated by Django 5.2 on 2026-09-17 09:53

import django.db.models.deletion
from django.db import migrations, models


def backfill(apps, schema_editor):
    """Derive each attachment's school from its uploader, else school #1.

    The GenericForeignKey target could be walked per ContentType, but the
    uploader is a reliable and far simpler signal: an attachment is created by
    someone inside the school it belongs to.
    """
    School = apps.get_model('authentication', 'School')
    school = School.objects.filter(slug='muzafar_alimbayev').first()
    if school is None:
        return

    Attachment = apps.get_model('achievement', 'Attachment')
    for row in Attachment.objects.select_related('uploaded_by').iterator():
        row.school_id = (
            row.uploaded_by.school_id if row.uploaded_by_id else None
        ) or school.pk
        row.save(update_fields=['school'])


def unbackfill(apps, schema_editor):
    apps.get_model('achievement', 'Attachment').objects.update(school=None)


class Migration(migrations.Migration):

    dependencies = [
        ("achievement", "0006_club_status"),
        ("authentication", "0039_auth_school_columns"),
    ]

    operations = [
        migrations.AddField(
            model_name="attachment",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="attachments",
                to="authentication.school",
            ),
        ),
        migrations.RunPython(backfill, unbackfill),
    ]
