# Generated by Django 5.2 on 2026-09-17 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("achievement", "0007_attachment_school"),
        ("authentication", "0039_auth_school_columns"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attachment",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="attachments",
                to="authentication.school",
            ),
        ),
    ]
