x-django-env:
  env_file: .env
  environment:
    DEBUG: ${DEBUG:-False}
    DJANGO_SETTINGS_MODULE: ${DJANGO_SETTINGS_MODULE:-core.settings}
    SECRET_KEY: ${SECRET_KEY}
    ALLOWED_HOSTS: ${ALLOWED_HOSTS:-*}
    DB_NAME: ${DB_NAME:-qadam}
    DB_USER: ${DB_USER:-qadam}
    DB_PASSWORD: ${DB_PASSWORD:-qadam}
    DB_HOST: db
    DB_PORT: 5432
    # AWS_... vars needed by boto3 at runtime:
    AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
    AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}

services:
  # export TAG=sha-$(git rev-parse --short=7 HEAD)
  appseed-app:
#    image: ghcr.io/pro100-almaz/qadam-analytics:${TAG}
    container_name: appseed_app
    restart: unless-stopped
    build: .
    env_file: .env
    environment:
      DEBUG: "False"
      DB_NAME: ${DB_NAME:-qadam}
      DB_USER: ${DB_USER:-qadam}
      DB_PASSWORD: ${DB_PASSWORD:-qadam}
      DB_HOST: db
      DB_PORT: 5432
      SERVICE_ACCOUNT_FILE_INTERNAL: /app/core/credentials/qadam_sheet_access.json
    depends_on: [db]
    # Expose ONLY to the host, not the internet:
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - ./staticfiles:/vol/static    # <-- host path for static
      - /var/www/school/media:/app/media
    networks: [db_network]

  db:
    container_name: postgres
    image: postgres:14-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME:-qadam}
      POSTGRES_USER: ${DB_USER:-qadam}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-qadam}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks: [db_network]

networks:
  db_network: { driver: bridge }

volumes:
  postgres_data:
