# Generated by Django 5.2 on 2025-04-02 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the lesson', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the lesson')),
                ('date', models.DateField(help_text='Date when the lesson takes place')),
                ('start_time', models.TimeField(help_text='Start time of the lesson')),
                ('end_time', models.TimeField(help_text='End time of the lesson')),
                ('subject', models.CharField(help_text='Subject taught in the lesson', max_length=100)),
                ('classroom', models.CharField(blank=True, help_text='Optional classroom or location info', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(help_text='Teacher responsible for this lesson', limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='lessons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lesson',
                'verbose_name_plural': 'Lessons',
                'ordering': ['date', 'start_time'],
            },
        ),
    ]
