# Generated by Django 5.2 on 2025-04-21 15:30

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='quarter',
            field=models.PositiveIntegerField(default=1, help_text='Quarter of the lesson', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AddField(
            model_name='studentgrade',
            name='comment',
            field=models.TextField(blank=True, help_text='Comment of the lesson'),
        ),
        migrations.AddField(
            model_name='studentgrade',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentgrade',
            name='points',
            field=models.PositiveIntegerField(default=0, help_text='Points of the lesson'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='classroom',
            field=models.ForeignKey(blank=True, help_text='Classroom of the lesson', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classroom', to='home.classroom'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='subject',
            field=models.ForeignKey(blank=True, help_text='Subject of the lesson', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject', to='home.subject'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(blank=True, help_text='Teacher responsible for this lesson', limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_points', models.PositiveIntegerField(default=0, help_text='Points of the lesson')),
                ('to_points', models.PositiveIntegerField(default=100, help_text='Points of the lesson')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson', to='home.lesson')),
            ],
        ),
    ]
