# Generated by Django 5.2 on 2025-04-21 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_lesson_quarter_studentgrade_comment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='progress',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='students',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='teacher',
        ),
        migrations.AddField(
            model_name='subject',
            name='average_grade',
            field=models.PositiveIntegerField(default=1, help_text='Grade of the lesson'),
        ),
        migrations.AddField(
            model_name='subject',
            name='classroom',
            field=models.ForeignKey(blank=True, help_text='Classroom of the lesson', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classroom', to='home.classroom'),
        ),
        migrations.AddField(
            model_name='subject',
            name='maximum_points',
            field=models.PositiveIntegerField(default=100, help_text='Maximum points of the lesson'),
        ),
        migrations.AddField(
            model_name='subject',
            name='progress',
            field=models.PositiveIntegerField(default=0, help_text='Progress of the lesson'),
        ),
        migrations.AddField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(blank=True, help_text='Teacher responsible for this lesson', limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='maximum_points',
            field=models.PositiveIntegerField(default=100, help_text='Maximum points of the lesson'),
        ),
    ]
