# Generated by Django 5.2 on 2025-04-05 15:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_classroom_subject_alter_lesson_classroom_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='grade',
            field=models.PositiveIntegerField(default=1, help_text='Grade of the lesson'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='progress',
            field=models.PositiveIntegerField(default=0, help_text='Progress of the lesson'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='students',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'student'}, related_name='lessons_attended', to=settings.AUTH_USER_MODEL),
        ),
    ]
