# Generated by Django 5.2 on 2025-04-22 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_lesson_classroom_remove_lesson_progress_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='status',
        ),
    ]
