# Generated by Django 5.2 on 2025-04-22 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_subject_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('planned', 'Planned'), ('disabled', 'Disabled')], default='disabled', max_length=20),
        ),
    ]
