# Generated by Django 5.2 on 2025-04-20 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_lesson_grade_lesson_progress_lesson_students'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='classroom',
            field=models.ForeignKey(help_text='Classroom of the lesson', on_delete=django.db.models.deletion.DO_NOTHING, related_name='classroom', to='home.classroom'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='subject',
            field=models.ForeignKey(help_text='Subject of the lesson', on_delete=django.db.models.deletion.DO_NOTHING, related_name='subject', to='home.subject'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(help_text='Teacher responsible for this lesson', limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='teacher', to=settings.AUTH_USER_MODEL),
        ),
    ]
