# Generated by Django 3.2.6 on 2025-04-20 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0004_lesson_grade_lesson_progress_lesson_students'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='grade',
            new_name='average_grade',
        ),
        migrations.AddField(
            model_name='lesson',
            name='maximum_points',
            field=models.PositiveIntegerField(default=0, help_text='Maximum points of the lesson'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='classroom',
            field=models.ForeignKey(help_text='Classroom of the lesson', on_delete=django.db.models.deletion.DO_NOTHING, related_name='classroom', to='home.classroom'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='subject',
            field=models.ForeignKey(help_text='Subject of the lesson', on_delete=django.db.models.deletion.DO_NOTHING, related_name='subject', to='home.subject'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(help_text='Teacher responsible for this lesson', limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='teacher', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='StudentGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.PositiveIntegerField(default=0, help_text='Grade of the lesson')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
