# Generated by Django 3.2.6 on 2025-04-20 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20250420_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('delayed', 'Delayed'), ('on schedule', 'On Schedule')], default='pending', max_length=20),
        ),
    ]
