# Generated by Django 5.2 on 2025-05-06 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_lessongroup_lesson_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='average_grade',
            new_name='average_points',
        ),
    ]
