# Generated by Django 5.2 on 2025-04-20 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_grade_lesson_average_grade_studentgrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='maximum_points',
            field=models.PositiveIntegerField(default=0, help_text='Maximum points of the lesson'),
        ),
    ]
