# Generated by Django 5.2 on 2025-05-06 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rename_average_grade_lesson_average_points'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='average_grade',
            new_name='average_points',
        ),
    ]
