# Generated by Django 5.2 on 2025-04-21 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_lesson_maximum_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('delayed', 'Delayed'), ('on schedule', 'On Schedule')], default='pending', max_length=20),
        ),
    ]
