# Generated by Django 5.2 on 2025-05-07 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_average_grade_subject_average_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_text',
            field=models.TextField(default=1, help_text='Template comment text'),
            preserve_default=False,
        ),
    ]
