# Generated by Django 5.2 on 2025-05-27 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_comment_comment_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='group',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='studentgrade',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='studentgrade',
            name='student',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='LessonGroup',
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
        migrations.DeleteModel(
            name='StudentGrade',
        ),
    ]
