# Generated by Django 5.2 on 2025-06-22 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_subject_added_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuarterGrader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.PositiveIntegerField(default=1)),
                ('average_points', models.PositiveIntegerField(default=1, help_text='Grade of the lesson')),
                ('cummulative_points', models.PositiveIntegerField(default=0)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.subject')),
            ],
        ),
    ]
