# Generated by Django 5.2 on 2025-06-26 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_remove_customuser_classroom_and_more'),
        ('home', '0013_alter_subject_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('planned', 'Planned'), ('disabled', 'Disabled'), ('archived', 'Archived')], default='disabled', max_length=20),
        ),
        migrations.AlterField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(blank=True, help_text='Teacher responsible for this lesson', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher', to='authentication.teacher'),
        ),
    ]
