# Generated by Django 5.2 on 2025-07-16 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0021_teacher_academic_degree_teacher_employment_type_and_more'),
        ('home', '0014_alter_subject_status_alter_subject_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(blank=True, help_text='Teacher responsible for this lesson', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taught_subjects', to='authentication.teacher'),
        ),
    ]
