# Generated by Django 5.2 on 2025-07-29 15:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_academicyear'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quartergrader',
            options={'ordering': ['quarter']},
        ),
        migrations.RenameField(
            model_name='quartergrader',
            old_name='cummulative_points',
            new_name='cumulative_points',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='classroom',
        ),
        migrations.AddField(
            model_name='subject',
            name='academic_year',
            field=models.ForeignKey(default=1, help_text='School year for this subject', on_delete=django.db.models.deletion.PROTECT, related_name='subjects', to='home.academicyear'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quartergrader',
            name='average_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quartergrader',
            name='quarter',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='quartergrader',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarters', to='home.subject'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='average_points',
            field=models.PositiveIntegerField(default=0, help_text='Current points earned (≤ maximum_points)', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='subject',
            name='maximum_points',
            field=models.PositiveIntegerField(default=100, help_text='Total possible points', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subject',
            name='progress',
            field=models.PositiveIntegerField(default=0, help_text='Progress percentage (0–100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterUniqueTogether(
            name='quartergrader',
            unique_together={('subject', 'quarter')},
        ),
    ]
