# Generated by Django 5.2 on 2025-08-12 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_quartergrader_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='academic_year',
            field=models.ForeignKey(blank=True, help_text='School year this classroom assignment applies to', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='classrooms', to='home.academicyear'),
        ),
    ]
