# Generated by Django 5.2 on 2025-08-23 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_classroom_academic_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='language_group',
            field=models.CharField(choices=[('kaz', 'KAZ'), ('rus', 'RUS'), ('eng', 'ENG')], default='kaz', max_length=20),
        ),
    ]
