# Generated by Django 5.2 on 2025-08-24 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_subject_language_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='language_group',
            field=models.CharField(choices=[('kaz', 'KAZ'), ('rus', 'RUS'), ('eng', 'ENG')], default='KAZ', max_length=20),
        ),
    ]
