# Generated by Django 5.2 on 2025-09-24 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_subject_language_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicyear',
            name='year',
            field=models.CharField(max_length=40),
        ),
    ]
