# Generated by Django 5.2 on 2026-01-25 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_academicyear_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicyear',
            name='archived',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='academicyear',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
