# Generated by Django 5.2 on 2026-01-25 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0031_remove_student_classroom_remove_teacher_classroom_and_more'),
        ('home', '0022_academicyear_archived_academicyear_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='subject',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='average_points',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='maximum_points',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='progress',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='teacher',
        ),
        migrations.CreateModel(
            name='ClassGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(default='A', max_length=10)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_groups', to='home.academicyear')),
                ('grade_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_groups', to='home.gradelevel')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('transferred', 'Transferred'), ('graduated', 'Graduated'), ('withdrawn', 'Withdrawn'), ('on_leave', 'On Leave')], default='active', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='home.academicyear')),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='home.classgroup')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='authentication.student')),
            ],
            options={
                'ordering': ['-academic_year__year', 'class_group'],
            },
        ),
        migrations.CreateModel(
            name='SubjectOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_points', models.PositiveIntegerField(default=100)),
                ('grading_strategy', models.CharField(choices=[('average', 'Average of all scores'), ('weighted', 'Weighted by assessment type'), ('cumulative', 'Cumulative points')], default='average', max_length=20)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_offerings', to='home.academicyear')),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_offerings', to='home.classgroup')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='home.subject')),
            ],
        ),
        migrations.CreateModel(
            name='TeachingAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('primary', 'Primary Teacher'), ('assistant', 'Assistant Teacher'), ('substitute', 'Substitute')], default='primary', max_length=20)),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_assignments', to='home.subjectoffering')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_assignments', to='authentication.teacher')),
            ],
        ),
        migrations.DeleteModel(
            name='ClassRoom',
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('student', 'academic_year'), name='unique_active_enrollment_per_year'),
        ),
        migrations.AlterUniqueTogether(
            name='subjectoffering',
            unique_together={('subject', 'class_group', 'academic_year')},
        ),
        migrations.AlterUniqueTogether(
            name='teachingassignment',
            unique_together={('offering', 'teacher')},
        ),
    ]
