# Generated by Django 5.2 on 2026-01-26 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_gradelevel_remove_subject_academic_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gradelevel',
            name='title',
        ),
    ]
