# Generated by Django 5.2 on 2026-05-04 11:38

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0033_historicalstudent'),
        ('home', '0024_remove_gradelevel_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalEnrollment',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('transferred', 'Transferred'), ('graduated', 'Graduated'), ('withdrawn', 'Withdrawn'), ('on_leave', 'On Leave')], default='active', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical enrollment',
                'verbose_name_plural': 'historical enrollments',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HomeroomTeacherAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['academic_year', 'status'], name='idx_enrollment_year_status'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['student', 'status'], name='idx_enrollment_student_status'),
        ),
        migrations.AddField(
            model_name='historicalenrollment',
            name='academic_year',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='home.academicyear'),
        ),
        migrations.AddField(
            model_name='historicalenrollment',
            name='class_group',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='home.classgroup'),
        ),
        migrations.AddField(
            model_name='historicalenrollment',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalenrollment',
            name='student',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='authentication.student'),
        ),
        migrations.AddField(
            model_name='homeroomteacherassignment',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeroom_assignments', to='home.academicyear'),
        ),
        migrations.AddField(
            model_name='homeroomteacherassignment',
            name='class_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeroom_assignments', to='home.classgroup'),
        ),
        migrations.AddField(
            model_name='homeroomteacherassignment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeroom_assignments', to='authentication.teacher'),
        ),
        migrations.AlterUniqueTogether(
            name='homeroomteacherassignment',
            unique_together={('class_group', 'academic_year')},
        ),
    ]
