# Generated by Django 5.2 on 2026-08-19 18:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0035_historicalstudent_medical_features_and_more"),
        ("home", "0026_academicyear_q1_end_academicyear_q1_start_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubjectAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField()),
                ("max_grade", models.PositiveIntegerField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("lesson", "Lesson"),
                            ("exam", "Exam"),
                            ("final", "Final"),
                        ],
                        default="lesson",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "offering",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="home.subjectoffering",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuarterGrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "grade",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(2),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                (
                    "quarter",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(4),
                        ]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "offering",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quarter_grades",
                        to="home.subjectoffering",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quarter_grades",
                        to="authentication.student",
                    ),
                ),
            ],
            options={
                "ordering": ["quarter", "student"],
                "unique_together": {("student", "offering", "quarter")},
            },
        ),
        migrations.CreateModel(
            name="SubjectGrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("grade", models.PositiveIntegerField()),
                ("comments", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grades",
                        to="home.subjectassignment",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grades",
                        to="authentication.student",
                    ),
                ),
            ],
            options={
                "ordering": ["student"],
                "unique_together": {("assignment", "student")},
            },
        ),
    ]
