# Generated by Django 5.2 on 2026-08-20 07:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0027_subjectassignment_quartergrade_subjectgrade"),
    ]

    operations = [
        migrations.AddField(
            model_name="subjectassignment",
            name="date",
            field=models.DateField(
                default=datetime.datetime(
                    2026, 8, 20, 7, 54, 14, 247392, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
    ]
