# Generated by Django 5.2 on 2026-08-20 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0028_subjectassignment_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subjectgrade",
            name="comments",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="subjectgrade",
            name="grade",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
