# Generated by Django 5.2 on 2026-09-04 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0036_add_new_roles"),
        ("home", "0029_alter_subjectgrade_comments_alter_subjectgrade_grade"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="enrollment",
            options={"ordering": ["-class_group__academic_year__year", "class_group"]},
        ),
        migrations.RemoveConstraint(
            model_name="enrollment",
            name="unique_active_enrollment_per_year",
        ),
        migrations.RemoveIndex(
            model_name="enrollment",
            name="idx_enrollment_year_status",
        ),
        migrations.AlterUniqueTogether(
            name="subjectoffering",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="enrollment",
            name="academic_year",
        ),
        migrations.RemoveField(
            model_name="historicalenrollment",
            name="academic_year",
        ),
        migrations.AlterUniqueTogether(
            name="homeroomteacherassignment",
            unique_together={("class_group",)},
        ),
        migrations.AddField(
            model_name="classgroup",
            name="category",
            field=models.CharField(
                choices=[("major", "Major"), ("minor", "Minor")],
                default="major",
                max_length=10,
            ),
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(
                fields=["class_group", "status"], name="idx_enrollment_class_status"
            ),
        ),
        migrations.RemoveField(
            model_name="subjectoffering",
            name="academic_year",
        ),
        migrations.RemoveField(
            model_name="homeroomteacherassignment",
            name="academic_year",
        ),
    ]
