# Generated by Django 5.2 on 2026-09-05 14:29

from django.db import migrations, models
from django.utils import timezone


def deduplicate_active_enrollments(apps, schema_editor):
    """Close out duplicate active enrollments so the new rules hold on old data.

    Keeps the newest active enrollment per (student, class_group), and the newest
    active major enrollment per (student, academic year); the rest become
    'transferred'.
    """
    Enrollment = apps.get_model('home', 'Enrollment')
    today = timezone.now().date()

    seen_groups = set()
    seen_majors = set()
    stale = []

    enrollments = Enrollment.objects.filter(status='active').select_related(
        'class_group'
    ).order_by('-start_date', '-id')

    for enrollment in enrollments:
        class_group = enrollment.class_group
        group_key = (enrollment.student_id, enrollment.class_group_id)
        if group_key in seen_groups:
            stale.append(enrollment.pk)
            continue
        seen_groups.add(group_key)

        if class_group is None or class_group.category != 'major':
            continue

        major_key = (enrollment.student_id, class_group.academic_year_id)
        if major_key in seen_majors:
            stale.append(enrollment.pk)
            continue
        seen_majors.add(major_key)

    if stale:
        Enrollment.objects.filter(pk__in=stale).update(
            status='transferred', end_date=today
        )


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0036_add_new_roles"),
        ("home", "0030_alter_enrollment_options_and_more"),
    ]

    operations = [
        migrations.RunPython(
            deduplicate_active_enrollments, migrations.RunPython.noop
        ),
        migrations.AddConstraint(
            model_name="enrollment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "active")),
                fields=("student", "class_group"),
                name="unique_active_enrollment_per_class_group",
            ),
        ),
    ]
