# Generated by Django 5.2 on 2026-09-17 09:53

import django.db.models.deletion
from django.db import migrations, models


def backfill(apps, schema_editor):
    """All existing academic data belongs to school #1.

    Order matters: the roots are stamped first, then SubjectOffering derives its
    school from the class group it already points at — so the denormalised hub
    column agrees with its parent from the moment it exists.
    """
    School = apps.get_model('authentication', 'School')
    school = School.objects.filter(slug='muzafar_alimbayev').first()
    if school is None:
        return

    for model in ('AcademicYear', 'ClassGroup', 'Subject'):
        apps.get_model('home', model).objects.update(school=school)

    SubjectOffering = apps.get_model('home', 'SubjectOffering')
    for offering in SubjectOffering.objects.select_related('class_group').iterator():
        offering.school_id = (
            offering.class_group.school_id if offering.class_group_id else school.pk
        )
        offering.save(update_fields=['school'])


def unbackfill(apps, schema_editor):
    for model in ('AcademicYear', 'ClassGroup', 'Subject', 'SubjectOffering'):
        apps.get_model('home', model).objects.update(school=None)


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0039_auth_school_columns"),
        ("home", "0034_classgroupcollection_major_minor_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="academicyear",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="academic_years",
                to="authentication.school",
            ),
        ),
        migrations.AddField(
            model_name="classgroup",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="class_groups",
                to="authentication.school",
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subjects",
                to="authentication.school",
            ),
        ),
        migrations.AddField(
            model_name="subjectoffering",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subject_offerings",
                to="authentication.school",
            ),
        ),
        migrations.RunPython(backfill, unbackfill),
    ]
