# Generated by Django 5.2 on 2026-09-17 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0040_school_not_null"),
        ("home", "0035_school_columns"),
    ]

    operations = [
        migrations.AlterField(
            model_name="academicyear",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="academic_years",
                to="authentication.school",
            ),
        ),
        migrations.AlterField(
            model_name="classgroup",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="class_groups",
                to="authentication.school",
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subjects",
                to="authentication.school",
            ),
        ),
        migrations.AlterField(
            model_name="subjectoffering",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subject_offerings",
                to="authentication.school",
            ),
        ),
    ]
