# Generated by Django 5.2 on 2026-10-01 13:43

import django.core.validators
from django.db import migrations, models


def backfill_quarter(apps, schema_editor):
    """Set each existing assignment's quarter from its date and its year's
    quarter bounds. Dates outside every quarter stay null."""
    AcademicYear = apps.get_model("home", "AcademicYear")
    SubjectAssignment = apps.get_model("home", "SubjectAssignment")
    for year in AcademicYear._base_manager.all():
        for q in (1, 2, 3, 4):
            start = getattr(year, f"q{q}_start")
            end = getattr(year, f"q{q}_end")
            if not (start and end):
                continue
            SubjectAssignment._base_manager.filter(
                offering__class_group__academic_year=year,
                date__range=(start, end),
                quarter__isnull=True,
            ).update(quarter=q)


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0044_assignment_category_translations"),
    ]

    operations = [
        migrations.AddField(
            model_name="subjectassignment",
            name="quarter",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(4),
                ],
            ),
        ),
        migrations.RunPython(backfill_quarter, migrations.RunPython.noop),
    ]
