# Generated by Django 5.2 on 2026-10-02 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0045_subjectassignment_quarter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subjectassignment",
            name="max_grade",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
