# Generated by Django 5.2 on 2025-07-05 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='action',
            field=models.CharField(choices=[('register', 'Registered'), ('login', 'Login'), ('grading', 'Grading'), ('psychological_state', 'Psychological_state')], default='register', max_length=20),
        ),
    ]
