# Generated by Django 5.2 on 2025-07-05 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0019_psychologicalstate_added_by'),
        ('notification', '0002_notification_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='psychologicalnotify',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.parent'),
        ),
    ]
