# Generated by Django 5.2 on 2026-05-04 11:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_psychologicalnotify_parent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gradingnotify',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='gradingnotify',
            name='notification',
        ),
        migrations.RemoveField(
            model_name='gradingnotify',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='loginnotify',
            name='notification',
        ),
        migrations.RemoveField(
            model_name='psychologicalnotify',
            name='notification',
        ),
        migrations.RemoveField(
            model_name='psychologicalnotify',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='psychologicalnotify',
            name='psychologist',
        ),
        migrations.RemoveField(
            model_name='registernotify',
            name='notification',
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='send_time',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='action',
        ),
        migrations.AddField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='message',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='notification',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('register', 'Registration'), ('login', 'Login'), ('grading', 'Grading'), ('psychological_state', 'Psychological State')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', '-created_at'], name='notificatio_user_id_c4d245_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='notificatio_user_id_543da6_idx'),
        ),
        migrations.DeleteModel(
            name='GradingNotify',
        ),
        migrations.DeleteModel(
            name='LoginNotify',
        ),
        migrations.DeleteModel(
            name='PsychologicalNotify',
        ),
        migrations.DeleteModel(
            name='RegisterNotify',
        ),
    ]
