server {
    listen 85;
    server_name dashboard.qadam.edu.kz;

    client_max_body_size 50m;

    # STATIC from shared volume
    location /static/ {
        alias /vol/static/;
        access_log off;
        expires 30d;
    }

    # Optional: if someone hits /media/*, redirect them to S3 (replace DOMAIN)
    # location /media/ {
    #     return 301 https://YOUR_AWS_S3_CUSTOM_DOMAIN$request_uri;
    # }

    location / {
        proxy_pass         http://appseed-app:8000;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_read_timeout 30s;
    }

    location /healthz { proxy_pass http://appseed-app:8000/healthz; access_log off; }
}
