from apps.home.api.views.dashboard import DashboardStatsAPIView, TeacherWorkloadAPIView
from apps.home.api.views.academic import (
    AcademicYearListAPIView,
    ClassGroupListAPIView,
    ClassGroupMinorGroupListAPIView,
    ClassGroupStudentListAPIView,
    RolloverAcademicYearAPIView,
)
from apps.home.api.views.students import (
    StudentListAPIView,
    StudentDetailAPIView,
    StudentProfileUpdateAPIView,
    PsychologicalStateCreateAPIView,
    PsychologicalStateDeleteAPIView,
    PsychologicalStateTemplateListAPIView,
    StudentMySubjectsAPIView,
    StudentMyTeachersAPIView,
    StudentClassmatesAPIView,
)
from apps.home.api.views.teachers import (
    TeacherListAPIView,
    TeacherDetailAPIView,
    TeacherProfileUpdateAPIView,
    ParentTeacherListAPIView,
)
from apps.home.api.views.subjects import (
    SubjectListAPIView,
    SubjectCreateAPIView,
    SubjectDetailAPIView,
    SubjectGradesAPIView,
    SubjectStatusAPIView,
    SubjectDeleteAPIView,
    MySubjectsListAPIView,
)
from apps.home.api.views.enrollments import EnrollmentListAPIView
from apps.home.api.views.parents import (
    ParentChildrenListAPIView,
    ParentChildDetailAPIView,
    ParentTeachersAPIView,
    ParentChildSubjectDetailAPIView,
)
from apps.home.api.views.assignments import (
    AssignmentCategoryListAPIView,
    SubjectAssignmentListCreateAPIView,
    SubjectAssignmentDetailAPIView,
    SubjectAssignmentGradeListCreateAPIView,
    SubjectGradeListAPIView,
    OfferingSubjectGradeListAPIView,
    SubjectGradeDetailAPIView,
    HomeroomSubjectAssignmentListAPIView,
    HomeroomSubjectGradeListAPIView,
)
from apps.home.api.views.quarter_grades import (
    OfferingQuarterGradeAPIView,
    HomeroomQuarterGradeListAPIView,
)
from apps.home.api.views.teacher_dashboard import (
    TeacherRoleDashboardAPIView,
    HomeroomMyClassAPIView,
    TeacherOfferingListAPIView,
    PsychologistDashboardAPIView,
    PsychologistStudentDetailAPIView,
    TeacherMyClassesAPIView,
    TeacherClassStudentsAPIView,
)

__all__ = [
    'DashboardStatsAPIView',
    'TeacherWorkloadAPIView',
    'AcademicYearListAPIView',
    'ClassGroupListAPIView',
    'ClassGroupMinorGroupListAPIView',
    'ClassGroupStudentListAPIView',
    'StudentListAPIView',
    'StudentDetailAPIView',
    'StudentProfileUpdateAPIView',
    'PsychologicalStateCreateAPIView',
    'PsychologicalStateDeleteAPIView',
    'PsychologicalStateTemplateListAPIView',
    'StudentMySubjectsAPIView',
    'StudentMyTeachersAPIView',
    'StudentClassmatesAPIView',
    'TeacherListAPIView',
    'TeacherDetailAPIView',
    'TeacherProfileUpdateAPIView',
    'ParentTeacherListAPIView',
    'SubjectListAPIView',
    'SubjectCreateAPIView',
    'SubjectDetailAPIView',
    'SubjectGradesAPIView',
    'SubjectStatusAPIView',
    'SubjectDeleteAPIView',
    'MySubjectsListAPIView',
    'RolloverAcademicYearAPIView',
    'EnrollmentListAPIView',
    'ParentChildrenListAPIView',
    'ParentChildDetailAPIView',
    'ParentTeachersAPIView',
    'ParentChildSubjectDetailAPIView',
    'TeacherRoleDashboardAPIView',
    'HomeroomMyClassAPIView',
    'TeacherOfferingListAPIView',
    'PsychologistDashboardAPIView',
    'PsychologistStudentDetailAPIView',
    'TeacherMyClassesAPIView',
    'TeacherClassStudentsAPIView',
    'AssignmentCategoryListAPIView',
    'SubjectAssignmentListCreateAPIView',
    'SubjectAssignmentDetailAPIView',
    'SubjectAssignmentGradeListCreateAPIView',
    'SubjectGradeListAPIView',
    'OfferingSubjectGradeListAPIView',
    'SubjectGradeDetailAPIView',
    'HomeroomSubjectAssignmentListAPIView',
    'HomeroomSubjectGradeListAPIView',
    'OfferingQuarterGradeAPIView',
    'HomeroomQuarterGradeListAPIView',
]
