# Generated by Django 5.2 on 2025-04-21 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_delete_student'),
        ('home', '0002_lesson_quarter_studentgrade_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='class_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.classroom'),
        ),
    ]
