# Generated by Django 3.2.6 on 2025-04-20 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('home', '0005_auto_20250420_1541'),
        ('authentication', '0004_remove_customuser_grade_customuser_school_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='customuser_ptr',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='customuser_ptr',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='supervisor',
        ),
        migrations.DeleteModel(
            name='Parent',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
