# Generated by Django 5.2 on 2025-04-23 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_customuser_class_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='occupation',
            field=models.CharField(blank=True, default=models.CharField(choices=[('parent', 'Parent'), ('teacher', 'Teacher'), ('student', 'Student'), ('supervisor', 'Supervisor'), ('principal', 'Principal'), ('admin', 'Admin')], default='student', max_length=20), max_length=50, null=True),
        ),
    ]
