# Generated by Django 5.2 on 2025-04-20 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_customuser_grade_customuser_school_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='customuser_ptr',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='customuser_ptr',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='supervisor',
        ),
        migrations.DeleteModel(
            name='Parent',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
