# Generated by Django 5.2 on 2025-04-23 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_customuser_occupation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='occupation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
