# Generated by Django 5.2 on 2025-05-06 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_customuser_occupation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='class_room',
            new_name='classroom',
        ),
    ]
