# Generated by Django 5.2 on 2025-05-31 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='avatars/%Y/%m/%d/'),
        ),
    ]
