# Generated by Django 5.2 on 2025-05-31 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='student_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
