# Generated by Django 5.2 on 2025-06-09 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_customuser_student_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('avatar', models.FileField(blank=True, null=True, upload_to='school_group/')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='school_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.schoolgroup'),
        ),
    ]
