# Generated by Django 5.2 on 2025-06-09 05:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_schoolgroup_customuser_school_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='PsychologicalState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('comment', models.TextField(blank=True, null=True)),
                ('score', models.PositiveIntegerField(default=1, help_text='На сколько звезд оцениваете состояние ученика?', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='physical_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.psychologicalstate'),
        ),
    ]
