# Generated by Django 5.2 on 2025-06-11 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_psychologicalstate_customuser_physical_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.FileField(blank=True, default='avatars/default/default-user.jpeg', null=True, upload_to='avatars/%Y/%m/%d/'),
        ),
    ]
