# Generated by Django 5.2 on 2025-06-11 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.FileField(default='avatars/default/default-user.jpeg', upload_to='avatars/%Y/%m/%d/'),
        ),
    ]
