# Generated by Django 5.2 on 2025-06-11 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_psychologicalstatetemplates_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psychologicalstatetemplates',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
