# Generated by Django 5.2 on 2025-06-28 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_remove_customuser_classroom_and_more'),
        ('home', '0014_alter_subject_status_alter_subject_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.classroom'),
        ),
    ]
