# Generated by Django 5.2 on 2025-07-05 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_teacher_classroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='psychologicalstate',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_psychological_states', to=settings.AUTH_USER_MODEL),
        ),
    ]
