# Generated by Django 5.2 on 2025-07-08 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0019_psychologicalstate_added_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='psychologicalstate',
            name='time_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
