# Generated by Django 5.2 on 2025-07-16 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0020_psychologicalstate_time_added'),
        ('home', '0014_alter_subject_status_alter_subject_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='academic_degree',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('full_time', 'Full-Time'), ('part_time', 'Part-Time')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='assigned_teachers', to='home.subject'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='working_hours',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
