# Generated by Django 5.2 on 2025-07-24 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0021_teacher_academic_degree_teacher_employment_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='student_id',
        ),
        migrations.AddField(
            model_name='parent',
            name='student',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.student'),
        ),
    ]
