# Generated by Django 5.2 on 2025-07-28 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0022_remove_parent_student_id_parent_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='student',
        ),
        migrations.AddField(
            model_name='parent',
            name='student_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
