# Generated by Django 5.2 on 2025-07-28 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0023_remove_parent_student_parent_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('parent', 'Parent'), ('teacher', 'Teacher'), ('homeroom_teacher', 'Homeroom Teacher'), ('student', 'Student'), ('supervisor', 'Supervisor'), ('principal', 'Principal'), ('admin', 'Admin')], default='student', max_length=20),
        ),
    ]
