# Generated by Django 5.2 on 2025-07-29 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0024_alter_customuser_role'),
        ('home', '0017_alter_quartergrader_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='student_id',
        ),
        migrations.AddField(
            model_name='parent',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='parent', to='authentication.student'),
        ),
        migrations.AddField(
            model_name='student',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='students', to='home.subject'),
        ),
    ]
