# Generated by Django 5.2 on 2025-08-12 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0025_remove_parent_student_id_parent_students_and_more'),
        ('home', '0018_classroom_academic_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='academic_year',
            field=models.ForeignKey(blank=True, help_text='Enrollment year for this student', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='home.academicyear'),
        ),
    ]
