# Generated by Django 5.2 on 2025-11-18 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0027_alter_customuser_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='school',
            field=models.CharField(choices=[('muzafar_alimbayev', 'Muzafar Alimbayev 21'), ('bukhar_zhyrau', 'Bukhar Zhyrau 19/1')], default='muzafar_alimbayev', max_length=20),
        ),
    ]
