# Generated by Django 5.2 on 2026-01-24 08:35

import apps.authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0028_migrate_roles_to_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.FileField(default='avatars/default/default-user.jpeg', upload_to='avatars/%Y/%m/%d/', validators=[apps.authentication.models.validate_avatar_size]),
        ),
    ]
