# Generated by Django 5.2 on 2026-01-25 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0029_alter_customuser_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
    ]
