# Generated by Django 5.2 on 2026-01-25 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0028_alter_customuser_school'),
        ('authentication', '0030_remove_customuser_role'),
    ]

    operations = [
    ]
