# Generated by Django 5.2 on 2026-04-30 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0031_remove_student_classroom_remove_teacher_classroom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolgroup',
            name='color',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
    ]
