# Generated by Django 5.2 on 2026-08-07 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0034_clubmanager"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalstudent",
            name="medical_features",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="medical_features",
            field=models.TextField(blank=True, null=True),
        ),
    ]
