# Generated by Django 5.2 on 2026-09-17 09:52

import uuid
from django.db import migrations, models


SCHOOLS = [
    ('muzafar_alimbayev', 'Muzafar Alimbayev 21'),
    ('bukhar_zhyrau', 'Bukhar Zhyrau 19/1'),
]


def seed_schools(apps, schema_editor):
    """Create the two tenants, keyed by the legacy CustomUser.school choices."""
    School = apps.get_model('authentication', 'School')
    for slug, name in SCHOOLS:
        School.objects.get_or_create(slug=slug, defaults={'name': name})


def unseed_schools(apps, schema_editor):
    School = apps.get_model('authentication', 'School')
    School.objects.filter(slug__in=[s for s, _ in SCHOOLS]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0036_add_new_roles"),
    ]

    operations = [
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Public identifier — this is what crosses the network, never the pk.",
                        unique=True,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Stable internal key used by migrations and script --school flags.",
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("short_name", models.CharField(blank=True, default="", max_length=50)),
                ("address", models.TextField(blank=True, default="")),
                (
                    "contact_phone",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "contact_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                ("timezone", models.CharField(default="Asia/Almaty", max_length=64)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Школа",
                "verbose_name_plural": "Школы",
                "ordering": ["name"],
            },
        ),
        migrations.RunPython(seed_schools, unseed_schools),
    ]
