# Generated by Django 5.2 on 2026-09-17 09:52

import uuid
from django.db import migrations, models


# Display names for the slugs that exist today. Anything else found in the
# legacy column gets a title-cased placeholder — rename it in the admin.
KNOWN_NAMES = {
    'muzafar_alimbayev': 'Muzafar Alimbayev 21',
    'bukhar_zhyrau': 'Bukhar Zhyrau 19/1',
}

DEFAULT_SLUG = 'muzafar_alimbayev'


def seed_schools(apps, schema_editor):
    """Create one tenant per distinct value of the legacy CustomUser.school.

    Originally this seeded two hardcoded rows, because the Sep 2 dump had 217
    users on 'muzafar_alimbayev' and a single anomalous 'bukhar_zhyrau' row.
    That is no longer the shape of the data: production now carries 290 and 120
    users across the two, with 99 enrolled students, 18 teachers and 7 class
    groups on the second — a live school, not an import artifact.

    So the set of tenants is read from the data rather than hardcoded, and a
    third value appearing in the column creates a third school instead of being
    silently merged into the first.

    `DEFAULT_SLUG` is always created even on an empty database, because the
    downstream backfills fall back to it for rows that reach no user.
    """
    School = apps.get_model('authentication', 'School')
    CustomUser = apps.get_model('authentication', 'CustomUser')

    slugs = {
        slug for slug in
        CustomUser.objects.values_list('school', flat=True).distinct()
        if slug
    }
    slugs.add(DEFAULT_SLUG)

    for slug in sorted(slugs):
        School.objects.get_or_create(
            slug=slug,
            defaults={'name': KNOWN_NAMES.get(slug, slug.replace('_', ' ').title())},
        )


def unseed_schools(apps, schema_editor):
    apps.get_model('authentication', 'School').objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0036_add_new_roles"),
    ]

    operations = [
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Public identifier — this is what crosses the network, never the pk.",
                        unique=True,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Stable internal key used by migrations and script --school flags.",
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("short_name", models.CharField(blank=True, default="", max_length=50)),
                ("address", models.TextField(blank=True, default="")),
                (
                    "contact_phone",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "contact_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                ("timezone", models.CharField(default="Asia/Almaty", max_length=64)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Школа",
                "verbose_name_plural": "Школы",
                "ordering": ["name"],
            },
        ),
        migrations.RunPython(seed_schools, unseed_schools),
    ]
