# Generated by Django 5.2 on 2026-09-17 09:52

import django.db.models.deletion
from django.db import migrations, models


def backfill(apps, schema_editor):
    """All existing rows belong to school #1 — the second school is not live."""
    School = apps.get_model('authentication', 'School')
    school = School.objects.filter(slug='muzafar_alimbayev').first()
    if school is None:
        return
    for model in ('SchoolGroup', 'PsychologicalStateTemplates', 'PsychologicalState'):
        apps.get_model('authentication', model).objects.update(school=school)


def unbackfill(apps, schema_editor):
    for model in ('SchoolGroup', 'PsychologicalStateTemplates', 'PsychologicalState'):
        apps.get_model('authentication', model).objects.update(school=None)


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0038_customuser_school"),
    ]

    operations = [
        migrations.AddField(
            model_name="psychologicalstate",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="psychological_states",
                to="authentication.school",
            ),
        ),
        migrations.AddField(
            model_name="psychologicalstatetemplates",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="psychological_state_templates",
                to="authentication.school",
            ),
        ),
        migrations.AddField(
            model_name="schoolgroup",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="school_groups",
                to="authentication.school",
            ),
        ),
        migrations.RunPython(backfill, unbackfill),
    ]
