# Generated by Django 5.2 on 2026-09-17 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("authentication", "0039_auth_school_columns"),
    ]

    operations = [
        migrations.AlterField(
            model_name="psychologicalstate",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="psychological_states",
                to="authentication.school",
            ),
        ),
        migrations.AlterField(
            model_name="psychologicalstatetemplates",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="psychological_state_templates",
                to="authentication.school",
            ),
        ),
        migrations.AlterField(
            model_name="schoolgroup",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="school_groups",
                to="authentication.school",
            ),
        ),
        migrations.AddConstraint(
            model_name="customuser",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("school__isnull", False), ("is_superuser", True), _connector="OR"
                ),
                name="user_has_school_unless_superuser",
            ),
        ),
    ]
