"""`Student.academic_year` (FK) becomes `Student.intake_year` (a label).

The FK read as the student's *current* year but was assigned once at creation
and never advanced — `rollover_academic_year` writes class groups and
enrollments, never this — so after one rollover it named a past year while the
student was enrolled in the present one. The authoritative year-by-year record
is Enrollment -> ClassGroup -> AcademicYear, which is multi-year and which a
single FK could never express.

Kept, as the one thing it was genuinely good for: when this student entered.
As a string that is true forever, survives a change of school untouched, and
stops being tenancy-coupled — years are per-school since §1b, so the FK had to
be re-pointed whenever a student moved or their profile failed its own
consistency check.

**Order matters here and the autogenerated version had it wrong.** Django
emitted RemoveField before AddField, which would have dropped every year before
anything could read it. Add, copy, then remove.

The copy is raw SQL rather than the historical ORM: `year` is a plain column on
`home_academicyear` and a correlated subquery does in one statement what a
RunPython loop would do in one query per student.
"""

from django.db import migrations, models

COPY = """
UPDATE {table} AS s
   SET intake_year = COALESCE(
       (SELECT y.year FROM home_academicyear y WHERE y.id = s.academic_year_id),
       '')
"""

#: No reverse copy. Going back would have to guess *which school's* row of a
#: given year to point at, and picking wrong is a cross-tenant write — exactly
#: what §1b spent a migration unpicking. The column is restored empty and the
#: labels are what a manual recovery would read.
UNCOPY = migrations.RunSQL.noop


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0042_retire_school_choices"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="intake_year",
            field=models.CharField(
                blank=True,
                default="",
                help_text='Academic year this student entered, e.g. "2025/2026". '
                          'Set once on creation; history, not a live pointer.',
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="historicalstudent",
            name="intake_year",
            field=models.CharField(
                blank=True,
                default="",
                help_text='Academic year this student entered, e.g. "2025/2026". '
                          'Set once on creation; history, not a live pointer.',
                max_length=40,
            ),
        ),
        migrations.RunSQL(
            sql=COPY.format(table='authentication_student'),
            reverse_sql=UNCOPY,
        ),
        migrations.RunSQL(
            sql=COPY.format(table='authentication_historicalstudent'),
            reverse_sql=UNCOPY,
        ),
        migrations.RemoveField(
            model_name="student",
            name="academic_year",
        ),
        migrations.RemoveField(
            model_name="historicalstudent",
            name="academic_year",
        ),
    ]
